app/core/models.py
from .. import db

Column = db.Column
relationship = db.relationship
ForeignKey = db.ForeignKey

class CRUDMixin(object):
    @classmethod
    def create(cls, **kwargs):
        """Create a new record and save it the database."""
        instance = cls(**kwargs)
        return instance.save()

    def update(self, commit=True, **kwargs):
        """Update specific fields of a record."""
        for attr, value in kwargs.items():
            setattr(self, attr, value)
        return commit and self.save() or self

    def save(self, commit=True):
        """Save the record."""
        db.session.add(self)
        if commit:
            db.session.commit()
        return self

    def delete(self, commit=True):
        """Remove the record from the database."""
        db.session.delete(self)
        return commit and db.session.commit()

class Model(CRUDMixin, db.Model):
    """Base model class that includes CRUD convenience methods."""

    __abstract__ = True

class PkModel(Model):
    """Base model class that includes CRUD convenience methods, plus adds a 'primary key' column named ``id``."""

    __abstract__ = True
    id = Column(db.Integer, primary_key=True)

    @classmethod
    def get_by_id(cls, record_id):
        """Get record by ID."""
        if any(
            (
                isinstance(record_id, str) and record_id.isdigit(),
                isinstance(record_id, (int, float)),
            )
        ):
            return cls.query.get(int(record_id))
        return None

app/core/__init__.py
from datetime import datetime
from flask import Blueprint, current_app
from flask_login import current_user
import logging
from uuid import uuid4

from .. import login_manager, db
from ..config import Environments

APP_NAME = "App"

core_bp = Blueprint("core", __name__, template_folder="templates")


@core_bp.app_context_processor
def context_processor():
    return dict(get_uuid=lambda: str(uuid4()), app_name=APP_NAME)


@core_bp.before_app_first_request
def before_app_first_request():
    if current_app.config["ENV"] == Environments.DEVELOPMENT:
        current_app.logger.setLevel(logging.DEBUG)

    from ..user.models import UserAccount

    login_manager.user_loader(lambda user_id: UserAccount.query.get(int(user_id)))


@core_bp.before_app_request
def before_app_request():
    if current_user.is_authenticated:
        current_user.last_active = datetime.utcnow()
        db.session.commit()


from .routes import core_bp

app/core/routes.py
from flask import redirect, render_template, url_for

from . import core_bp
from ..auth import login_required


@core_bp.route("/")
@core_bp.route("/home")
@login_required()
def home():
    return render_template("core/home.html")
    # return redirect(url_for("user.profile"))

app/templates/core/home.html
{% extends 'core/layout.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="d-flex align-content-center">
        <div class="h3">
            Hi
        </div>
    </div>
</div>
{% endblock %}

app/templates/core/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{{ app_name }}</title>
    {% block header %}{% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    </script>
</head>

<body class="min-vh-100">
    <header class="sticky-top bg-white">
        <nav class="navbar navbar-expand-lg navbar-light shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% if current_user.is_authenticated %}
                            {{ url_for('core.home') }}
                        {% else %}
                            {{ url_for('auth.login') }}
                        {% endif %}">
                    <img class="img-fluid" style="width: 100%; height: 30px"
                        src="{{ url_for('static', filename='images/logo_full.svg') }}" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Manage
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% if current_user.role.name != "Dispatcher" %}
                                <li><a class="dropdown-item" href="{{ url_for('data.manage_truck') }}">
                                    <i class="fa-solid fa-truck"></i>
                                    Truck
                                </a></li>
                                <li><a class="dropdown-item" href="{{ url_for('data.manage_employee') }}">
                                    <i class="fa-solid fa-address-card"></i>
                                    Employee
                                </a></li>
                                {% endif %}
                                {% if current_user.role.name == "Administrator" %}
                                <li><a class="dropdown-item" href="{{ url_for('data.manage_user') }}">
                                    <i class="fa-solid fa-user"></i>
                                    Users
                                </a></li>
                                {% endif %}
                                <li><a class="dropdown-item" href="{{ url_for('data.manage_trip') }}">
                                    <i class="fa-solid fa-suitcase-rolling"></i>
                                    Trips
                                </a></li>                                
                            </ul>
                        </li>
                        {% endif %}

                        <!-- Login/Logout button -->
                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">
                                <i class="fa-solid fa-arrow-right-from-bracket fa-lg"></i>
                                Logout
                            </a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">
                                <i class="fa-solid fa-arrow-right-to-bracket fa-lg"></i>
                                Login
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="bg-light">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        {% set id=get_uuid() %}
        <div class="alert alert-{{ category }} border-bottom text-break text-center mb-0" id="{{ id }}">
            <div class="d-flex flex-nowrap align-items-center">
                <div class="col-1"></div>
                <div class="col-10">
                    {{ message }}
                </div>
                <div class="col-1">
                    <a href="#" class="link-primary" onclick="$('#{{ id }}').remove()">
                        <i class="fas fa-times-circle"></i>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <div class="container-fluid pb-5">
            <div class="row">
                <div class="col-12">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
    {% block js %}{% endblock %}
</body>