app/data/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    ValidationError,
    StringField,
    DecimalField,
    SelectField,
    IntegerField,
    DateField,
    BooleanField,
)
from wtforms.validators import (
    DataRequired,
    EqualTo,
    NumberRange,
    Regexp,
    StopValidation,
)

# import phonenumbers

from .models import DriverType, Gender, InterprovincialTrip, SchoolLevel


class DependsOf:
    def __init__(self, fields: dict, extra_validators=[], message=None):
        self.message = message
        self.fields = fields
        self.extra_validators = extra_validators

    def __call__(self, form, field):
        for k, v in self.fields.items():
            if hasattr(form, k) and getattr(form, k).data != v:
                return

        for validator in self.extra_validators:
            validator(form, field)
        return


class RegisterTruckForm(FlaskForm):
    id = StringField("ID", validators=[DataRequired()])
    model = StringField("Model", validators=[DataRequired()])
    weight = DecimalField("Weight", validators=[DataRequired()])
    fuel_type = SelectField(
        "Fuel Type", choices=["Gasoline", "Diesel"], validators=[DataRequired()]
    )
    driver = SelectField("Driver", validators=[DataRequired()])
    truck_type = SelectField(
        "Type", validators=[DataRequired()], choices=["Lightweight", "Heavy"]
    )

    # Lightweight truck fields
    max_speed = DecimalField(
        "Max. Speed",
        validators=[
            DependsOf(
                {"truck_type": "Lightweight"},
                extra_validators=[DataRequired(), NumberRange(min=0)],
            )
        ],
        default=0,
    )
    max_load = DecimalField(
        "Max. Load",
        validators=[
            DependsOf(
                {"truck_type": "Lightweight"},
                extra_validators=[DataRequired(), NumberRange(min=0)],
            )
        ],
        default=0,
    )

    # Heavy truck fields
    spend_by_kilometer = DecimalField(
        "Spend by Km.",
        validators=[
            DependsOf(
                {"truck_type": "Heavy"},
                extra_validators=[DataRequired(), NumberRange(min=0)],
            )
        ],
        default=0,
    )
    length = DecimalField(
        "Length",
        validators=[
            DependsOf(
                {"truck_type": "Heavy"},
                extra_validators=[DataRequired(), NumberRange(min=0)],
            )
        ],
        default=0,
    )
    width = DecimalField(
        "Width",
        validators=[
            DependsOf(
                {"truck_type": "Heavy"},
                extra_validators=[DataRequired(), NumberRange(min=0)],
            )
        ],
        default=0,
    )
    height = DecimalField(
        "Height",
        validators=[
            DependsOf(
                {"truck_type": "Heavy"},
                extra_validators=[DataRequired(), NumberRange(min=0)],
            )
        ],
        default=0,
    )


class RegisterEmployeeForm(FlaskForm):
    phone = StringField(
        "Phone",
        validators=[
            DataRequired(),
            Regexp(
                "\+?(53)? *5\d{7}",
                message="The phone must be a valid Cuban phone number. Ex: +53 55776611",
            ),
        ],
    )
    name = StringField("Name", validators=[DataRequired()])
    gender = SelectField(
        "Gender",
        validators=[DataRequired()],
        # coerce=Gender,
        choices=[x.name.replace("_", " ").capitalize() for x in Gender],
    )
    school_level = SelectField(
        "School level",
        validators=[DataRequired()],
        # coerce=SchoolLevel,
        choices=[x.name.replace("_", " ").capitalize() for x in SchoolLevel],
    )
    laboral_experience = IntegerField(
        "Laboral experience",
        validators=[
            NumberRange(
                min=0,
                message="The laboral experience must be a positive integer in years",
            )
        ],
    )
    address = StringField("Address", validators=[DataRequired()])
    employee_type = SelectField(
        "Type", validators=[DataRequired()], choices=["Driver", "Administrative", "Other"], default="Other"
    )

    # Driver fields
    driver_type = SelectField(
        "Driver type",
        validators=[
            DependsOf({"employee_type": "Driver"}, extra_validators=[DataRequired()])
        ],
        choices=[x.name.replace("_", " ").capitalize() for x in DriverType],
    )
    driver_evaluation = IntegerField(
        "Driver evaluation",
        validators=[
            DependsOf(
                {"employee_type": "Driver"},
                extra_validators=[DataRequired(), NumberRange(min=0)],
            ),
        ],
        default=0,
    )

    # Administrative fields
    administrative_position = StringField(
        "Administrative position",
        validators=[
            DependsOf(
                {"employee_type": "Administrative"}, extra_validators=[DataRequired()]
            )
        ],
    )


class RegisterTripForm(FlaskForm):
    date = DateField("Date", validators=[DataRequired()])
    load = DecimalField(
        "Load", validators=[DataRequired(), NumberRange(min=0)], default=0
    )
    destination = StringField("Destination", validators=[DataRequired()])
    distance = DecimalField("Distance", validators=[DataRequired(), NumberRange(min=0)])
    truck = SelectField("Truck", validators=[DataRequired()])

    is_interprovincial = BooleanField("Is interprovincial?", default=False)
    return_date = DateField(
        "Return date",
        validators=[
            DependsOf({"is_interprovincial": True}, extra_validators=[DataRequired()])
        ],
    )

app/data/__init__.py
from flask import Blueprint

data_bp = Blueprint("data", __name__, template_folder="templates")

from .routes import data_bp

app/data/routes.py
import codecs
from datetime import date, timedelta
from io import BytesIO, StringIO
import itertools
import re
import itertools
import csv
from typing import List, TextIO

from flask import flash, redirect, render_template, url_for, send_file
from sqlalchemy import func, not_, select, not_

from ..user.models import UserAccount

from ..auth import login_required, role_required
from . import data_bp
from .. import db
from .forms import RegisterEmployeeForm, RegisterTripForm, RegisterTruckForm
from .models import (
    Administrative,
    Driver,
    Employee,
    Gender,
    HeavyTruck,
    InterprovincialTrip,
    LightweightTruck,
    SchoolLevel,
    Trip,
    Truck,
)


@data_bp.route("/register/truck", methods=["GET", "POST"])
@role_required(["Administrator", "Manager"])
def register_truck():
    form = RegisterTruckForm()
    drivers: List[Driver] = Driver.query.all()
    form.driver.choices = [x.employee.name for x in drivers]

    if form.validate_on_submit():
        index = -1
        for i in drivers:
            if i.employee.name == form.driver.data:
                index = i.employee_id

        if index != -1:
            Truck.create(
                id=form.id.data,
                weight=float(form.weight.data),
                model=form.model.data,
                fuel_type=form.fuel_type.data,
                driver_id=index,
            )

            if form.truck_type.data == "Lightweight":
                LightweightTruck.create(
                    truck_id=form.id.data,
                    max_speed=float(form.max_speed.data),
                    max_load=float(form.max_load.data),
                )
                flash("Lightweight truck registration successfull!!", "success")
            else:
                HeavyTruck.create(
                    truck_id=form.id.data,
                    spend_by_kilometer=float(form.spend_by_kilometer.data),
                    length=float(form.length.data),
                    width=float(form.width.data),
                    height=float(form.height.data),
                )
                flash("Heavy truck registration successfull!!", "success")

            return redirect(url_for("data.manage_truck"))
        elif form.is_submitted():
            flash("Invalid driver data", "danger")

    return render_template("data/register_truck.html", form=form)


@data_bp.route("/manage/employee")
@role_required(["Administrator", "Manager"])
def manage_employee():
    headers = (
        "ID",
        "Name",
        "Phone",
        "Gender",
        "School level",
        "Laboral experience",
        "Address",
    )
    administratives_headers = headers + ("Position",)
    drivers_headers = headers + ("Driver type", "Evaluation")

    administratives_data = Administrative.query.all()
    drivers_data = Driver.query.all()

    def get_data(e: Employee):
        return (
            e.id,
            e.name,
            e.phone,
            str(e.gender.name).capitalize(),
            str(e.school_level.name).capitalize().replace("_", " "),
            f"{e.laboral_experience} years",
            e.address,
        )

    return render_template(
        "data/manage_employee.html",
        administratives_headers=administratives_headers,
        administratives_data=list(
            map(lambda x: get_data(x.employee) + (x.position,), administratives_data)
        ),
        drivers_headers=drivers_headers,
        drivers_data=list(
            map(
                lambda x: get_data(x.employee) + (x.type.name, x.evaluation),
                drivers_data,
            )
        ),
    )


@data_bp.route("/manage/truck")
@role_required(["Administrator", "Manager"])
def manage_truck():
    headers = (
        "ID",
        "Weight",
        "Model",
        "Fuel type",
    )
    lightweight_headers = headers + ("Max. Speed", "Max. Load")
    heavy_headers = headers + ("Spend/Km.", "Length", "Width", "Height")

    lightweight_data = LightweightTruck.query.all()
    heavy_data = HeavyTruck.query.all()

    def get_data(t: Truck):
        return [
            t.id,
            t.weight,
            t.model,
            str(t.fuel_type).capitalize(),
        ]

    return render_template(
        "data/manage_truck.html",
        lightweight_headers=lightweight_headers,
        lightweight_data=list(
            map(
                lambda x: get_data(x.truck) + [x.max_speed, x.max_load],
                lightweight_data,
            )
        ),
        heavy_headers=heavy_headers,
        heavy_data=list(
            map(
                lambda x: get_data(x.truck)
                + [x.spend_by_kilometer, x.length, x.width, x.height],
                heavy_data,
            )
        ),
    )


@data_bp.route("/register/employee", methods=["GET", "POST"])
@role_required(["Administrator", "Manager"])
def register_employee():
    form = RegisterEmployeeForm()

    if form.validate_on_submit():
        # Normalize phone number
        phone = re.match("\+?(53)? *(5\d{7})", form.phone.data)
        # Normalize name
        name = str.join(" ", map(str.capitalize, form.name.data.split()))

        e = Employee.create(
            phone=f"+53 {phone[2]}",
            name=name,
            gender=Gender[form.gender.data.replace(" ", "_").upper()],
            school_level=SchoolLevel[form.school_level.data.replace(" ", "_").upper()],
            laboral_experience=form.laboral_experience.data,
            address=form.address.data,
        )
        if form.employee_type.data == "Driver":
            Driver.create(
                employee_id=e.id,
                type=form.driver_type.data,
                evaluation=form.driver_evaluation.data,
            )

            flash("Driver registration successfull!!", "success")
        elif form.employee_type.data == "Administrative":
            Administrative.create(
                employee_id=e.id, position=form.administrative_position.data
            )

            flash("Administrative registration successfull!!", "success")
        else:
            flash("Employee registration successfull!!", "success")

        return redirect(url_for("data.manage_employee"))
    elif form.is_submitted():
        flash("Invalid employee data", "danger")

    return render_template("data/register_employee.html", form=form)


@data_bp.route("/register/trip", methods=["GET", "POST"])
@login_required()
def register_trip():
    form = RegisterTripForm()
    trucks: List[Truck] = Truck.query.all()
    form.truck.choices = [x.id for x in trucks]

    if form.validate_on_submit():
        if not any(map(lambda x: x.id == form.truck.data, trucks)):
            flash("Invalid driver data", "danger")
        else:
            t = Trip.create(
                date=form.date.data,
                load=float(form.load.data),
                distance=float(form.distance.data),
                destination=form.destination.data,
                truck_id=form.truck.data,
            )

            if form.is_interprovincial.data:
                InterprovincialTrip.create(
                    trip_id=t.id, return_date=form.return_date.data
                )

            flash("Successfull trip register", "success")
            return redirect(url_for("data.manage_trip"))

    return render_template("data/register_trip.html", form=form)


@data_bp.route("/manage/trip")
@login_required()
def manage_trip():
    trips = Trip.query.all()

    def get_data(x: Trip):
        i = InterprovincialTrip.query.filter_by(trip_id=x.id).first()
        return (
            x.id,
            x.destination,
            x.date,
            x.load,
            x.distance,
            bool(i),
            x.truck_id,
            i.return_date if i else "-",
        )

    return render_template(
        "data/manage_trip.html",
        trips_headers=(
            "ID",
            "Destination",
            "Date",
            "Load (Kg.)",
            "Distance (Km.)",
            "Interprovincial?",
            "Truck id",
            "Return date",
        ),
        trips_data=list(map(get_data, trips)),
    )


@data_bp.route("/generate-paysheet")
@role_required(["Administrator", "Manager"])
def generate_paysheet():
    def get_data():
        return itertools.chain(
            (
                db.session.query(
                    Employee.name,
                    func.count(Trip.id) * 30 + 4500,
                )
                .join(InterprovincialTrip.trip)
                .join(Trip.truck)
                .join(Truck.driver)
                .join(Driver.employee)
                .filter(Driver.type == "A")
                .group_by(Driver.employee_id)
                # .union(db.session.query(Employee.name, 4500).filter(Employee.id.not_in()))
                .all()
            ),
            (
                db.session.query(Employee.name, 10 * Driver.evaluation + 4500)
                .join(Driver.employee)
                .filter(Driver.type == "B")
                .all()
            ),
            (db.session.query(Employee.name, 4700).join(Administrative.employee).all()),
            (
                db.session.query(Employee.name, 4500)
                .filter(
                    Employee.id.not_in(select(Driver.employee_id)),
                    Employee.id.not_in(select(Administrative.employee_id)),
                )
                .all()
            ),
        )

    return render_template(
        "data/paysheet.html", headers=["Name", "Salary (USD)"], employees=get_data()
    )


@data_bp.route("/statistics/trucks")
@login_required()
def statistics_trucks():
    range = (date.today() - timedelta(days=7), date.today())
    sub = select(Trip.truck_id).filter(Trip.date.between(*range)).subquery()

    data = (
        db.session.query(
            Truck.id,
            func.sum(Trip.distance),
            func.avg(Trip.distance),
            func.sum(Trip.load),
        )
        .join(Trip.truck)

app/templates/data/_header.html
<div class="row justify-content-center">
    <div class="col-auto">
        <div class="row justify-content-center py-2">
            <div class="col-auto h3">
                {{ title }}
            </div>
        </div>
    </div>
</div>

app/templates/data/_table.html
<div class="border rounded bg-white">
    <div class="row border-bottom py-2">
        <div class="col-12">
            <span class="fw-bold">
                {{ title }}
            </span>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                {% for head in headers %}
                <th scope="col">{{ head }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
            <tr>
                {% for item in row %}
                <td>{{ item }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

app/templates/data/manage_employee.html
{% extends 'core/layout.html' %}
{% block content %}
<div class="row justify-content-center mx-5 my-3">
    <div class="d-flex mb-3">
        <div class="py-2">
            <div class="h2">
                <i class="fa-solid fa-address-card h3"></i>
                Employees
            </div>
        </div>
    </div>
    <div class="mb-4">
        <a class="btn btn-primary me-2" href="{{ url_for('data.register_employee') }}" role="button">
            <i class="fa-solid fa-plus"></i>
            Register Employee
        </a>
        <a class="btn btn-success" href="{{ url_for('data.generate_paysheet') }}" role="button">
            <i class="fa-solid fa-rug"></i>
            Generate Paysheet
        </a>
    </div>
    <hr>
    {% with title='Administratives', headers=administratives_headers, data=administratives_data %}
    {% include 'data/_table.html' %}
    {% endwith %}

    <div class="mb-5"></div>

    {% with title='Drivers', headers=drivers_headers, data=drivers_data %}
    {% include 'data/_table.html' %}
    {% endwith %}
</div>
{% endblock %}

app/templates/data/manage_trip.html
{% extends 'core/layout.html' %}
{% block content %}
<div class="row justify-content-center mx-5 my-3">
    <div class="d-flex mb-3">
        <div class="py-2">
            <div class="h2">
                <i class="fa-solid fa-suitcase-rolling"></i>
                Trips
            </div>
        </div>
    </div>
    <div class="mb-4">
        <a class="btn btn-primary me-2" href="{{ url_for('data.register_trip') }}" role="button">
            <i class="fa-solid fa-plus"></i>
            Register Trip
        </a>
        <a class="btn btn-success" href="{{ url_for('data.save_trip_backup') }}" role="button">
            <i class="fa-solid fa-plus"></i>
            Save data backup
        </a>
    </div>
    <hr>
    {% with title='Trips', headers=trips_headers, data=trips_data %}
    {% include 'data/_table.html' %}
    {% endwith %}
</div>
{% endblock %}

app/templates/data/manage_truck.html
{% extends 'core/layout.html' %}
{% block content %}
<div class="row justify-content-center mx-5 my-3">
    <div class="d-flex mb-3">
        <div class="py-2">
            <div class="h2">
                <i class="fa-solid fa-truck"></i>
                Trucks
            </div>
        </div>
        <div class="ml-auto p-2">
            <a class="btn btn-secondary" href="{{ url_for('data.register_truck') }}" role="button">Register</a>
        </div>
        <div class="ml-auto p-2">
            <a class="btn btn-secondary" href="{{ url_for('data.statistics_trucks') }}" role="button">Statistics</a>
        </div>
    </div>
    <hr>
    {% with title='Lightweight', headers=lightweight_headers, data=lightweight_data %}
    {% include 'data/_table.html' %}
    {% endwith %}

    <div class="mb-5"></div>

    {% with title='Heavy', headers=heavy_headers, data=heavy_data %}
    {% include 'data/_table.html' %}
    {% endwith %}
</div>
{% endblock %}

app/templates/data/manage_user.html
{% extends 'core/layout.html' %}
{% block content %}
<div class="row justify-content-center mx-5 my-3">
    <div class="d-flex mb-3">
        <div class="py-2">
            <div class="h2">
                <i class="fa-solid fa-user"></i>
                Users
            </div>
        </div>
    </div>
    <div class="mb-4">
        <a class="btn btn-primary" href="{{ url_for('auth.register') }}" role="button">
            <i class="fa-solid fa-plus"></i>
            Register user
        </a>
    </div>
    <hr>
    {% with title='Users', headers=headers, data=data %}
    {% include 'data/_table.html' %}
    {% endwith %}
</div>
{% endblock %}

app/templates/data/paysheet.html
{% extends 'core/layout.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-11 d-flex mb-3">
        <div class="h3">
            Paysheet
        </div>
    </div>
    {% with title='', headers=headers, data=employees %}
    {% include 'data/_table.html' %}
    {% endwith %}
</div>
{% endblock %}

app/templates/data/register_employee.html
{% extends 'core/layout.html' %}
{% block content %}

{% with title="Register employee" %}
{% include 'data/_header.html' %}
{% endwith %}
<div class="row justify-content-center">
    <div class="col-11 col-md-6 col-lg-4">
        <div class="col-12 border rounded bg-white p-3">
            <form method="POST">
                {{ form.csrf_token }}
                <div class="col-12 mb-3">
                    {% with field=form.name %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3">
                    {% with field=form.phone %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3">
                    {% with field=form.gender %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3">
                    {% with field=form.address %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3">
                    {% with field=form.school_level %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3">
                    {% with field=form.laboral_experience %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3">
                    {% with field=form.employee_type %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3" id="driver_type_container" style="display: none;">
                    {% with field=form.driver_type %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3" id="driver_evaluation_container" style="display: none;">
                    {% with field=form.driver_evaluation %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3" id="administrative_position_container" style="display: none;">
                    {% with field=form.administrative_position %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="row col-12 justify-content-center border-top g-0 pt-3">
                    <button class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        const onEmployeeTypeChange = (x) => {
            const value = $("#employee_type").val();
            // alert(value);
            if (value == "Driver") {
                $("#driver_type_container").show();
                $("#driver_evaluation_container").show();
                $("#administrative_position_container").hide();
            } 
            else if (value == "Administrative") {
                $("#driver_type_container").hide();
                $("#driver_evaluation_container").hide();
                $("#administrative_position_container").show();
            } else {
                $("#driver_type_container").hide();
                $("#driver_evaluation_container").hide();
                $("#administrative_position_container").hide();
            }
        };
        $("#employee_type").change(onEmployeeTypeChange);
        onEmployeeTypeChange();
    });
</script>
{% endblock %}

app/templates/data/register_trip.html
{% extends 'core/layout.html' %}
{% block content %}

{% with title="Register trip" %}
{% include 'data/_header.html' %}
{% endwith %}
<div class="row justify-content-center">
    <div class="col-11 col-md-6 col-lg-4">
        <div class="col-12 border rounded bg-white p-3">
            <form method="POST">
                {{ form.csrf_token }}
                <div class="col-12 mb-3">
                    {% with field=form.destination %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3">
                    {% with field=form.date %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3">
                    {% with field=form.load %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3">
                    {% with field=form.distance %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3">
                    {% with field=form.truck %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="col-12 mb-3">
                    <div class="form-check">
                        {{ form.is_interprovincial(class='form-check-input') }}
                        {{ form.is_interprovincial.label(class='form-check-label') }}
                    </div>                    
                </div>
                <div class="col-12 mb-3" id="return_date_container" style="display: none;">
                    {% with field=form.return_date %}
                    {% include 'core/components/inputs/floating_label.html' %}
                    {% endwith %}
                </div>
                <div class="row col-12 justify-content-center border-top g-0 pt-3">
                    <button class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        const onChange = (x) => {
            const value = $("input[name=is_interprovincial]:checked").val();
            // alert(value);
            if (value == "y") {
                $("#return_date_container").show();
            } else {
                $("#return_date_container").hide();
            }
        };
        $("#is_interprovincial").change(onChange);
        onChange();
    });
</script>
{% endblock %}

app/templates/data/statistics_trucks.html
{% extends 'core/layout.html' %}
{% block content %}
<div class="row justify-content-center mx-5 my-3">
    <div class="d-flex mb-3">
        <div class="py-2">
            <div class="h2">
                <i class="fa-solid fa-bar-chart h3"></i>
                Statistics
            </div>
        </div>
    </div>
    {% with title='', headers=headers, data=data %}
    {% include 'data/_table.html' %}
    {% endwith %}
</div>
{% endblock %}